# Generated by Django 5.2.5 on 2025-08-12 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الوسم')),
                ('slug', models.SlugField(unique=True, verbose_name='الرابط المختصر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وسم',
                'verbose_name_plural': 'الوسوم',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='الملف')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video', 'فيديو'), ('document', 'مستند'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الوسائط')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'وسائط',
                'verbose_name_plural': 'مكتبة الوسائط',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الصفحة')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='المقتطف')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='إظهار في القائمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_pages', to='cms.media', verbose_name='الصورة المميزة')),
            ],
            options={
                'verbose_name': 'صفحة',
                'verbose_name_plural': 'الصفحات',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='آيديا للاستشارات والحلول التسويقية', max_length=200, verbose_name='عنوان الموقع')),
                ('site_description', models.TextField(default='خبراء التسويق والإبداع', verbose_name='وصف الموقع')),
                ('contact_email', models.EmailField(default='info@ideateeam.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('contact_phone', models.CharField(default='773171477', max_length=20, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط إنستغرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط لينكد إن')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='معرف Google Analytics')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('site_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo', to='cms.media', verbose_name='شعار الموقع')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقال')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='المقتطف')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='وصف SEO')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقال مميز')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.category', verbose_name='التصنيف')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_posts', to='cms.media', verbose_name='الصورة المميزة')),
                ('tags', models.ManyToManyField(blank=True, to='cms.tag', verbose_name='الوسوم')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'مقالات المدونة',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
