# Generated by Django 5.2.5 on 2025-08-14 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta_business', 'Meta Business'), ('twitter', 'X (Twitter)'), ('google_analytics', 'Google Analytics'), ('google_ads', 'Google Ads'), ('linkedin', 'LinkedIn')], max_length=50, unique=True, verbose_name='المنصة')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=500, verbose_name='سر API')),
                ('access_token', models.TextField(blank=True, verbose_name='رمز الوصول')),
                ('refresh_token', models.TextField(blank=True, verbose_name='رمز التحديث')),
                ('additional_settings', models.JSONField(default=dict, verbose_name='إعدادات إضافية')),
                ('is_active', models.BooleanField(default=False, verbose_name='نشط')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات التكامل',
                'verbose_name_plural': 'إعدادات التكامل',
            },
        ),
        migrations.CreateModel(
            name='VisitorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='مفتاح الجلسة')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('referrer', models.URLField(blank=True, verbose_name='المصدر')),
                ('page_url', models.URLField(verbose_name='رابط الصفحة')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الصفحة')),
                ('visit_duration', models.PositiveIntegerField(default=0, verbose_name='مدة الزيارة (ثانية)')),
                ('is_bounce', models.BooleanField(default=True, verbose_name='زيارة ارتداد')),
                ('device_type', models.CharField(blank=True, max_length=20, verbose_name='نوع الجهاز')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='المتصفح')),
                ('operating_system', models.CharField(blank=True, max_length=50, verbose_name='نظام التشغيل')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='البلد')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الزيارة')),
            ],
            options={
                'verbose_name': 'تتبع زائر',
                'verbose_name_plural': 'تتبع الزوار',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحملة')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google Ads'), ('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn')], max_length=50, verbose_name='المنصة')),
                ('campaign_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الحملة في المنصة')),
                ('objective', models.CharField(max_length=100, verbose_name='هدف الحملة')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الميزانية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('paused', 'متوقفة'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('target_audience', models.JSONField(default=dict, verbose_name='الجمهور المستهدف')),
                ('campaign_settings', models.JSONField(default=dict, verbose_name='إعدادات الحملة')),
                ('performance_data', models.JSONField(default=dict, verbose_name='بيانات الأداء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'حملة إعلانية',
                'verbose_name_plural': 'الحملات الإعلانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقرير')),
                ('report_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع التقرير')),
                ('date_from', models.DateField(verbose_name='من تاريخ')),
                ('date_to', models.DateField(verbose_name='إلى تاريخ')),
                ('website_analytics', models.JSONField(default=dict, verbose_name='تحليلات الموقع')),
                ('form_submissions', models.JSONField(default=dict, verbose_name='إرسالات النماذج')),
                ('visitor_insights', models.JSONField(default=dict, verbose_name='رؤى الزوار')),
                ('platform_performance', models.JSONField(default=dict, verbose_name='أداء المنصات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تقرير تحليلات',
                'verbose_name_plural': 'تقارير التحليلات',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم النموذج')),
                ('form_type', models.CharField(choices=[('consultation', 'طلب استشارة'), ('marketing_solutions', 'الحلول التسويقية'), ('creative_solutions', 'الحلول الإبداعية'), ('technical_solutions', 'الحلول التقنية'), ('comprehensive_solutions', 'حلول آيديا الشاملة'), ('contact', 'تواصل معنا'), ('custom', 'نموذج مخصص')], max_length=50, verbose_name='نوع النموذج')),
                ('description', models.TextField(blank=True, verbose_name='وصف النموذج')),
                ('form_schema', models.JSONField(default=dict, verbose_name='هيكل النموذج')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'نموذج ديناميكي',
                'verbose_name_plural': 'النماذج الديناميكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', models.JSONField(verbose_name='بيانات الإرسال')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='new', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.dynamicform', verbose_name='النموذج')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='معالج بواسطة')),
            ],
            options={
                'verbose_name': 'إرسال نموذج',
                'verbose_name_plural': 'إرسالات النماذج',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('analytics', 'تحليلات'), ('ads_performance', 'أداء الإعلانات'), ('social_insights', 'رؤى اجتماعية'), ('engagement', 'التفاعل'), ('reach', 'الوصول')], max_length=50, verbose_name='نوع التقرير')),
                ('report_data', models.JSONField(verbose_name='بيانات التقرير')),
                ('date_from', models.DateField(verbose_name='من تاريخ')),
                ('date_to', models.DateField(verbose_name='إلى تاريخ')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.integrationsettings', verbose_name='التكامل')),
            ],
            options={
                'verbose_name': 'تقرير منصة',
                'verbose_name_plural': 'تقارير المنصات',
                'ordering': ['-generated_at'],
            },
        ),
    ]
