# Generated by Django 4.2.7 on 2025-10-15 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cms", "0002_integrationsettings_visitortracking_adcampaign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المشروع"),
                ),
                ("description", models.TextField(verbose_name="وصف المشروع")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "تخطيط"),
                            ("in_progress", "قيد التنفيذ"),
                            ("review", "مراجعة"),
                            ("completed", "مكتمل"),
                            ("on_hold", "متوقف"),
                            ("cancelled", "ملغي"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ البداية")),
                ("end_date", models.DateField(verbose_name="تاريخ النهاية")),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="الميزانية",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="نسبة الإنجاز"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدير المشروع",
                    ),
                ),
                (
                    "team_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="team_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أعضاء الفريق",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشروع",
                "verbose_name_plural": "المشاريع",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="المفتاح"
                    ),
                ),
                ("value", models.TextField(verbose_name="القيمة")),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعداد النظام",
                "verbose_name_plural": "إعدادات النظام",
            },
        ),
        migrations.AlterModelOptions(
            name="adcampaign",
            options={
                "ordering": ["-created_date"],
                "verbose_name": "حملة إعلانية",
                "verbose_name_plural": "الحملات الإعلانية",
            },
        ),
        migrations.RemoveField(
            model_name="adcampaign",
            name="campaign_id",
        ),
        migrations.RemoveField(
            model_name="adcampaign",
            name="campaign_settings",
        ),
        migrations.RemoveField(
            model_name="adcampaign",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="adcampaign",
            name="performance_data",
        ),
        migrations.RemoveField(
            model_name="adcampaign",
            name="target_audience",
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="account_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="معرف الحساب الإعلاني"
            ),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="created_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ الإنشاء"),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="data",
            field=models.JSONField(default=dict, verbose_name="البيانات الخام للحملة"),
        ),
        migrations.AddField(
            model_name="adcampaign",
            name="external_id",
            field=models.CharField(
                default="",
                max_length=255,
                unique=True,
                verbose_name="المعرف الخارجي للحملة",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="الميزانية",
            ),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="أنشئ بواسطة",
            ),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="تاريخ الانتهاء"
            ),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="name",
            field=models.CharField(max_length=255, verbose_name="اسم الحملة"),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="objective",
            field=models.CharField(blank=True, max_length=255, verbose_name="الهدف"),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="platform",
            field=models.CharField(
                choices=[
                    ("meta_business", "Meta Business"),
                    ("twitter", "X (Twitter)"),
                    ("google_ads", "Google Ads"),
                ],
                max_length=50,
                verbose_name="المنصة",
            ),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاريخ البدء"),
        ),
        migrations.AlterField(
            model_name="adcampaign",
            name="status",
            field=models.CharField(max_length=50, verbose_name="الحالة"),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المهمة"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف المهمة"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "قائمة المهام"),
                            ("in_progress", "قيد التنفيذ"),
                            ("review", "مراجعة"),
                            ("done", "مكتملة"),
                        ],
                        default="todo",
                        max_length=20,
                        verbose_name="الحالة",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("medium", "متوسطة"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الاستحقاق"
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الساعات المقدرة",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="الساعات الفعلية",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مُعين إلى",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أنشئ بواسطة",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="cms.project",
                        verbose_name="المشروع",
                    ),
                ),
            ],
            options={
                "verbose_name": "مهمة",
                "verbose_name_plural": "المهام",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "تم تعيين مهمة"),
                            ("task_completed", "تم إكمال مهمة"),
                            ("project_update", "تحديث مشروع"),
                            ("deadline_reminder", "تذكير موعد نهائي"),
                            ("system_alert", "تنبيه النظام"),
                            ("message_received", "رسالة جديدة"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.project",
                        verbose_name="المشروع المرتبط",
                    ),
                ),
                (
                    "related_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms.task",
                        verbose_name="المهمة المرتبطة",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="الموضوع")),
                ("content", models.TextField(verbose_name="المحتوى")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستلم",
                    ),
                ),
                (
                    "related_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cms.project",
                        verbose_name="المشروع المرتبط",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "رسالة",
                "verbose_name_plural": "الرسائل",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("admin", "مدير النظام"),
                            ("client", "عميل"),
                            ("team_member", "عضو فريق"),
                            ("manager", "مدير مشروع"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("company", models.CharField(blank=True, max_length=200, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف المستخدم",
                "verbose_name_plural": "ملفات المستخدمين",
            },
        ),
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("page_view", "مشاهدة صفحة"),
                            ("user_login", "تسجيل دخول"),
                            ("project_created", "إنشاء مشروع"),
                            ("task_completed", "إكمال مهمة"),
                            ("form_submission", "إرسال نموذج"),
                        ],
                        max_length=20,
                        verbose_name="نوع المقياس",
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="القيمة")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحليل",
                "verbose_name_plural": "التحليلات",
                "ordering": ["-created_at"],
            },
        ),
    ]
